**Problem - 1: Array Creation:**


1. Empty array (2×2)


In [39]:
import numpy as np

arr_empty = np.empty((2,2))
arr_empty


array([[1.40607411e-315, 0.00000000e+000],
       [5.45310572e-090, 8.75588656e+169]])

2. Ones array (4×2)

In [40]:
arr_ones = np.ones((4,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Array filled with a given value

In [41]:
arr_full = np.full((3,3), 7)   # example fill value = 7
arr_full


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

4. Zeros like another array

In [42]:
a = np.array([[1,2,3],[4,5,6]])
zeros_like = np.zeros_like(a)
zeros_like


array([[0, 0, 0],
       [0, 0, 0]])

5. Ones like another array

In [43]:
ones_like = np.ones_like(a)
ones_like


array([[1, 1, 1],
       [1, 1, 1]])

6. Convert list to numpy array

In [44]:
new_list = [1,2,3,4]
np_array = np.array(new_list)
np_array


array([1, 2, 3, 4])

**PROBLEM 2 — Array Manipulation**

1. Array from 10 to 49


In [45]:
arr = np.arange(10, 50)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. 3×3 matrix from 0 to 8

In [46]:
mat = np.arange(9).reshape(3,3)
mat


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Identity matrix

In [47]:
identity = np.eye(3)
identity


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Random array of size 30 + mean


In [48]:
random_arr = np.random.random(30)
random_arr.mean()


np.float64(0.48094311422035474)

5. 10×10 random array + min & max

In [49]:
arr10 = np.random.random((10,10))
arr10.min(), arr10.max()


(np.float64(0.003711049719800963), np.float64(0.9830657240675091))

6. Zero array of size 10; replace 5th element with 1

In [50]:
z = np.zeros(10)
z[4] = 1
z


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Reverse array

In [51]:
arr = np.array([1,2,0,0,4,0])
arr[::-1]


array([0, 4, 0, 0, 2, 1])

8. 2D array with 1 border, 0 inside

In [52]:
border = np.ones((5,5))
border[1:-1, 1:-1] = 0
border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

9. 8×8 checkerboard pattern

In [53]:
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
checker


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**PROBLEM 3 — Array Operations**

In [54]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


1. Add arrays

In [55]:
x + y

array([[ 6,  8],
       [10, 13]])

2. Subtract arrays

In [56]:
x - y


array([[-4, -4],
       [-4, -3]])

3. Multiply array with integer

In [57]:
x * 3


array([[ 3,  6],
       [ 9, 15]])

4. Square of each element


x ** 2


5. Dot products

In [58]:
np.dot(v, w)       # v.w

np.dot(x, v)       # x.v

np.dot(x, y)       # x.y


array([[19, 22],
       [50, 58]])

6. Concatenate x & y (row-wise), v & w (column-wise)

In [59]:
# rows
np.concatenate((x, y), axis=0)

# columns
np.column_stack((v, w))


array([[ 9, 11],
       [10, 12]])

7. Concatenate x & v → why error?x has shape (2,2)

v has shape (2,)
They do not match in dimension for concatenation → numpy raises ValueError.

In [60]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**PROBLEM 4 — Matrix Operations**

In [61]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


1. Prove A · A⁻¹ = I

In [62]:
np.dot(A, np.linalg.inv(A))


array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

2. Show AB ≠ BA

In [63]:
np.dot(A,B)
np.dot(B,A)


array([[36, 44],
       [13, 16]])

3. Prove (AB)ᵀ = Bᵀ Aᵀ

In [64]:
lhs = np.transpose(np.dot(A,B))
rhs = np.dot(B.T, A.T)
lhs, rhs

(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

Matrix form: AX = B


In [65]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])


Solution using inverse

In [66]:
X = np.linalg.inv(A).dot(B)
X


array([ 2.,  1., -2.])

Better method (recommended): solve()

In [67]:
np.linalg.solve(A,B)


array([ 2.,  1., -2.])